### ISSUE TITLE
关于代码的问题

### ISSUE THREAD

**Issue by ThomasVercetti** [vonfeng/DPLink#3]
您好，在我使用Foursquare-Twitter数据集执行代码的过程中发生了如下问题：
Traceback (most recent call last):
  File "run.py", line 106, in <module>
    experiments = service.list_experiments()
  File "E:\anaconda\Anaconda\lib\site-packages\mlflow\tracking\service.py", line 68, in list_experiments
    return self.store.list_experiments()
  File "E:\anaconda\Anaconda\lib\site-packages\mlflow\store\file_store.py", line 82, in list_experiments
    return [self.get_experiment(exp_id) for exp_id in list_subdirs(self.root_directory)]
  File "E:\anaconda\Anaconda\lib\site-packages\mlflow\store\file_store.py", line 82, in <listcomp>
    return [self.get_experiment(exp_id) for exp_id in list_subdirs(self.root_directory)]
  File "E:\anaconda\Anaconda\lib\site-packages\mlflow\store\file_store.py", line 118, in get_experiment
    return self._get_experiment(experiment_dirs[0])
  File "E:\anaconda\Anaconda\lib\site-packages\mlflow\store\file_store.py", line 110, in _get_experiment
    meta = read_yaml(experiment_dir_path, FileStore.META_DATA_FILE_NAME)
  File "E:\anaconda\Anaconda\lib\site-packages\mlflow\utils\file_utils.py", line 153, in read_yaml
    raise Exception("Yaml file '%s' does not exist." % file_path)
Exception: Yaml file '/data1/output\.trash\meta.yaml' does not exist.
请问这个该怎么解决？
以及我按照Readme中提到的向Dr. Yong li 发邮件请求数据集，但是可能教授过于繁忙，至今未收到回复，请问您能提供一份ISP-Weibo的数据集给我吗？我的邮箱是1246377298@qq.com

**Comment by vonfeng** [comment]
1. mlflow 这里是用来记录实验结果，方便查看对比的，如果使用有问题，可以直接去掉相关代码，不影响整体。这个问题我不曾见过，也许你可以了解下mlflow的使用，可能会有所帮助
2. 不好意思，这个数据集我个人不能直接传播。你可以重新发送邮件给我（ feng-j16 at mails dot tsinghua dot edu dot cn），我会帮忙转发和提醒一下

**Comment by ThomasVercetti** [comment]
李老师您好，我们在GitHub上看到了您使用的两个数据集：ISP-Weibo数据集与Foursquare-Twitter Data数据集，我们在我们的系统中希望能够应用到您的ISP-Weibo数据集来实现数据可视化，希望您能够允许。
姓名：李皓
学校：安徽工程大学计算机与信息学院计算机科学与技术系162班
&nbsp;


---原始邮件---
发件人: "Jie Feng"<notifications@github.com&gt;
发送时间: 2020年4月22日(周三) 晚上6:52
收件人: "vonfeng/DPLink"<DPLink@noreply.github.com&gt;;
抄送: "Author"<author@noreply.github.com&gt;;"ThomasVercetti"<1246377298@qq.com&gt;;
主题: Re: [vonfeng/DPLink] 关于代码的问题 (#3)




  
mlflow 这里是用来记录实验结果，方便查看对比的，如果使用有问题，可以直接去掉相关代码，不影响整体。这个问题我不曾见过，也许你可以了解下mlflow的使用，可能会有所帮助 

不好意思，这个数据集我个人不能直接传播。你可以重新发送邮件给我，我会帮忙转发和提醒一下
